# Generated by Django 2.1.5 on 2019-06-06 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Anonymous', 'Anonymous'), ('Bush', 'Bush'), ('Clinton', 'Clinton'), ('Ghandi', 'Ghandi'), ('Kennedy', 'Kennedy'), ('Merkel', 'Merkel'), ('Obama', 'Obama'), ('Putin', 'Putin'), ('Trump', 'Trump')], default='Anonymous', max_length=15)),
            ],
            managers=[
                ('authors', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_string', models.CharField(max_length=200)),
                ('message_class', models.CharField(choices=[('B', 'BULLYING'), ('U', 'UNCLASSIFIED'), ('R', 'RACIST'), ('N', 'NORMAL'), ('S', 'SEXIST')], max_length=1)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored', to='chat.Author')),
            ],
            managers=[
                ('messages', django.db.models.manager.Manager()),
            ],
        ),
    ]
