# Generated by Django 2.1.5 on 2019-06-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='concatenated_classes',
            field=models.CharField(default='NNNN', max_length=10),
            preserve_default=False,
        ),
    ]
