# Generated by Django 3.2.3 on 2021-05-29 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
